spring:
  application:
    name: BaseSpringApp

  datasource:
    driver-class-name: org.postgresql.Driver
    username: 'postgres'
    password: '123456'
    url: 'jdbc:postgresql://localhost:5432/base_db'

  jpa:
    hibernate:
      ddl-auto: create-drop

  security:
    user:
      name: admin
      password: 123456

  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
            value:
              default:
                type:
